export default {
  data: {
    itemPage: {
      itemHeader: {
        id: "133970391",
        name: "Wings",
        imgUrl:
          "https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/photos/77ac95bf-347d-4805-8da0-cd7f40269b05-retina-large.jpg",
        imgUrlList: [],
        description:
          "Choose from any of our five famous sauces: Lemon Pepper, Lime Chile, Spicy Honey BBQ, Buffalo, and HOT. Served with ranch.",
        displayString: "+$10.99",
        unitAmount: 1099,
        currency: "USD",
        decimalPlaces: 2,
        specialInstructionsMaxLength: 500,
        calloutDisplayString: "",
        minAgeRequirement: 0,
        foodAlcoholConstraint: "REQUIRES_NONE",
        dashpassExclusiveItemDisabled: false,
        isDashpassExclusive: false,
        quantityLimit: 0,
        servingSizeDisplayString: null,
        banners: [],
        caloricInfoDisplayString: "",
        dietaryTagsList: [],
        menuId: "1275487",
        reviewData: {
          ratingDisplayString: "93% (33)",
          reviewCount: "",
          consumerItemRating: {
            rating: {
              ratingType: null,
              ratingValue: null,
              __typename: "RatingInfo",
            },
            ratingDisplayString: "",
            __typename: "ConsumerItemRating",
          },
          __typename: "ReviewData",
        },
        __typename: "ItemHeader",
      },
      optionLists: [
        {
          type: "extra_option",
          id: "266826944",
          name: "Wings Size",
          subtitle: "Select 1",
          selectionNode: "single_select",
          minNumOptions: 1,
          maxNumOptions: 1,
          minAggregateOptionsQuantity: null,
          maxAggregateOptionsQuantity: null,
          minOptionChoiceQuantity: null,
          maxOptionChoiceQuantity: null,
          numFreeOptions: 0,
          isOptional: false,
          storeId: null,
          titleLayout: null,
          options: [
            {
              id: "1486838972",
              name: "12 Pc",
              unitAmount: 900,
              currency: "USD",
              displayString: "+$9.00",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1498365144",
              name: "16 Pc",
              unitAmount: 1500,
              currency: "USD",
              displayString: "+$15.00",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1498365145",
              name: "25 Pc",
              unitAmount: 3800,
              currency: "USD",
              displayString: "+$38.00",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838973",
              name: "50 Pc",
              unitAmount: 6600,
              currency: "USD",
              displayString: "+$66.00",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838974",
              name: "6 Pc",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
          ],
          validationType: "DEFAULT",
          flattenedDefaultNodes: [],
          __typename: "OptionList",
        },
        {
          type: "extra_option",
          id: "266826945",
          name: "Flavor Choice",
          subtitle: "Select 1",
          selectionNode: "single_select",
          minNumOptions: 1,
          maxNumOptions: 1,
          minAggregateOptionsQuantity: null,
          maxAggregateOptionsQuantity: null,
          minOptionChoiceQuantity: null,
          maxOptionChoiceQuantity: null,
          numFreeOptions: 0,
          isOptional: false,
          storeId: null,
          titleLayout: null,
          options: [
            {
              id: "1486838975",
              name: "Buffalo (Mild)",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838976",
              name: "Hot",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838977",
              name: "Lemon Pepper",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838978",
              name: "Lime Chile",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838979",
              name: "Spicy Honey BBQ",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
          ],
          validationType: "DEFAULT",
          flattenedDefaultNodes: [],
          __typename: "OptionList",
        },
        {
          type: "extra_option",
          id: "266826946",
          name: "Dipping Choice",
          subtitle: "Select 1",
          selectionNode: "single_select",
          minNumOptions: 1,
          maxNumOptions: 1,
          minAggregateOptionsQuantity: null,
          maxAggregateOptionsQuantity: null,
          minOptionChoiceQuantity: null,
          maxOptionChoiceQuantity: null,
          numFreeOptions: 0,
          isOptional: false,
          storeId: null,
          titleLayout: null,
          options: [
            {
              id: "1486838980",
              name: "Blu Cheese",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
            {
              id: "1486838981",
              name: "Ranch",
              unitAmount: 0,
              currency: "USD",
              displayString: "",
              decimalPlaces: 2,
              nextCursor: null,
              caloricInfoDisplayString: "",
              chargeAbove: 0,
              chargeAboveDisplayString: "",
              defaultQuantity: 0,
              dietaryTagsList: [],
              optionTagsList: [],
              imgUrl: "",
              __typename: "FeedOption",
            },
          ],
          validationType: "DEFAULT",
          flattenedDefaultNodes: [],
          __typename: "OptionList",
        },
      ],
      presetCarousels: [
        {
          name: "Select popular options for your order",
          description: "",
          selectedPresetIndex: null,
          presets: [
            {
              name: "#1 • Ordered recently by 40+ others",
              specialInstructions: null,
              description: "6 Pc • Buffalo (Mild) • Ranch",
              displayPrice: "$10.99",
              dietaryTagsList: [],
              flattenedDefaultNodes: [
                {
                  __typename: "DefaultOption",
                  parentId: "266826944",
                  id: "1486838974",
                  name: "6 Pc",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826945",
                  id: "1486838975",
                  name: "Buffalo (Mild)",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826946",
                  id: "1486838981",
                  name: "Ranch",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
              ],
              __typename: "Preset",
            },
            {
              name: "#2 • Ordered recently by 20+ others",
              specialInstructions: null,
              description: "12 Pc • Lemon Pepper • Ranch",
              displayPrice: "$19.99",
              dietaryTagsList: [],
              flattenedDefaultNodes: [
                {
                  __typename: "DefaultOption",
                  parentId: "266826944",
                  id: "1486838972",
                  name: "12 Pc",
                  nextCursor: null,
                  displayString: "+$9.00",
                  unitAmount: 900,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826945",
                  id: "1486838977",
                  name: "Lemon Pepper",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826946",
                  id: "1486838981",
                  name: "Ranch",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
              ],
              __typename: "Preset",
            },
            {
              name: "#3 • Ordered recently by 20+ others",
              specialInstructions: null,
              description: "12 Pc • Buffalo (Mild) • Ranch",
              displayPrice: "$19.99",
              dietaryTagsList: [],
              flattenedDefaultNodes: [
                {
                  __typename: "DefaultOption",
                  parentId: "266826944",
                  id: "1486838972",
                  name: "12 Pc",
                  nextCursor: null,
                  displayString: "+$9.00",
                  unitAmount: 900,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826945",
                  id: "1486838975",
                  name: "Buffalo (Mild)",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
                {
                  __typename: "DefaultOption",
                  parentId: "266826946",
                  id: "1486838981",
                  name: "Ranch",
                  nextCursor: null,
                  displayString: "",
                  unitAmount: 0,
                  currency: "USD",
                  decimalPlaces: 2,
                  selectedQuantity: 1,
                  caloricInfoDisplayString: "",
                  dietaryTagsList: [],
                  imgUrl: "",
                },
              ],
              __typename: "Preset",
            },
          ],
          __typename: "PresetCarousel",
        },
      ],
      itemType: "HAS_OPTIONS",
      itemCarousels: [],
      itemPreferences: {
        id: "user_preferences_id",
        title: "User Preferences",
        specialInstructions: {
          title: "Add Special Instructions",
          characterMaxLength: 500,
          isEnabled: true,
          placeholderText:
            "Add any special requests (e.g., food allergies, extra spicy, etc.) and the store will do its best to accommodate you.",
          __typename: "ItemSpecialInstructions",
        },
        substitutionPreferences: {
          title: "If item is unavailable",
          substitutionPreferencesList: [
            {
              id: "OPTION_TYPE_SUBSTITUTE",
              displayString: "Go with merchant recommendation",
              isDefault: true,
              value: "substitute",
              __typename: "ItemSubstitutionPreference",
            },
            {
              id: "OPTION_TYPE_REFUND",
              displayString: "Refund this item",
              isDefault: false,
              value: "refund",
              __typename: "ItemSubstitutionPreference",
            },
            {
              id: "OPTION_TYPE_CONTACT",
              displayString: "Contact me",
              isDefault: false,
              value: "contact",
              __typename: "ItemSubstitutionPreference",
            },
            {
              id: "OPTION_TYPE_CANCEL",
              displayString: "Cancel the entire order",
              isDefault: false,
              value: "cancel",
              __typename: "ItemSubstitutionPreference",
            },
          ],
          __typename: "ItemSubstitutionPreferences",
        },
        __typename: "ItemPreferences",
      },
      additionalDescriptions: [],
      __typename: "ItemPage",
    },
  },
  extensions: {
    requestInfo: {
      version: 1,
      requestId: "c10f9f6c-3ce4-4152-8802-56c8ac35b624",
      correlationId: "c10f9f6c-3ce4-4152-8802-56c8ac35b624",
    },
  },
};
