export default {
  uuid: "_DkmcMa6Eee_I_WOUqzMIQ",
  id: "26269186",
  restaurant_id: 548814,
  menu_category_name: "Appetizers",
  menu_category_id: "2911815",
  name: "Wings",
  description: "Choice of sauce. Served with ranch.",
  price: {
    amount: 0,
    currency: "USD",
  },
  delivery_price: {
    amount: 0,
    currency: "USD",
  },
  pickup_price: {
    amount: 0,
    currency: "USD",
  },
  tax: 10.25,
  tax_rate: {
    name: "RestaurantTax",
    rate: 10.25,
    included_in_item_price: false,
  },
  miscellaneous_taxes: [],
  minimum_cart_total: {
    amount: 0,
    currency: "USD",
  },
  combinable_with_coupons: true,
  sequence: 1,
  minimum_price_variation: {
    amount: 1099,
    currency: "USD",
  },
  delivery_minimum_price_variation: {
    amount: 1099,
    currency: "USD",
  },
  pickup_minimum_price_variation: {
    amount: 1099,
    currency: "USD",
  },
  maximum_price_variation: {
    amount: 7999,
    currency: "USD",
  },
  delivery_maximum_price_variation: {
    amount: 7999,
    currency: "USD",
  },
  pickup_maximum_price_variation: {
    amount: 7999,
    currency: "USD",
  },
  available: true,
  choice_category_list: [
    {
      uuid: "DsWnUerJEeeYzZHkxaa6Mg",
      id: "11335230",
      name: "Choose a size",
      min_choice_options: 1,
      max_choice_options: 1,
      choice_option_list: [
        {
          id: "44127953",
          description: "6 Piece Wings",
          price: {
            amount: 1099,
            currency: "USD",
          },
          delivery_price: {
            amount: 1099,
            currency: "USD",
          },
          pickup_price: {
            amount: 1099,
            currency: "USD",
          },
          tax: 10.25,
          tax_rate: {
            name: "RestaurantTax",
            rate: 10.25,
            included_in_item_price: false,
          },
          choice_category_list: [],
          price_changes: {},
          sequence: 1,
          defaulted: false,
          available: true,
        },
        {
          id: "44127954",
          description: "12 Piece Wings",
          price: {
            amount: 1999,
            currency: "USD",
          },
          delivery_price: {
            amount: 1999,
            currency: "USD",
          },
          pickup_price: {
            amount: 1999,
            currency: "USD",
          },
          tax: 10.25,
          tax_rate: {
            name: "RestaurantTax",
            rate: 10.25,
            included_in_item_price: false,
          },
          choice_category_list: [],
          price_changes: {},
          sequence: 2,
          defaulted: false,
          available: true,
        },
        {
          id: "194637219",
          description: "16 Piece Wings",
          price: {
            amount: 2599,
            currency: "USD",
          },
          delivery_price: {
            amount: 2599,
            currency: "USD",
          },
          pickup_price: {
            amount: 2599,
            currency: "USD",
          },
          tax: 10.25,
          tax_rate: {
            name: "RestaurantTax",
            rate: 10.25,
            included_in_item_price: false,
          },
          choice_category_list: [],
          price_changes: {},
          sequence: 3,
          defaulted: false,
          available: true,
        },
        {
          id: "194637220",
          description: "25 Piece Wings",
          price: {
            amount: 3999,
            currency: "USD",
          },
          delivery_price: {
            amount: 3999,
            currency: "USD",
          },
          pickup_price: {
            amount: 3999,
            currency: "USD",
          },
          tax: 10.25,
          tax_rate: {
            name: "RestaurantTax",
            rate: 10.25,
            included_in_item_price: false,
          },
          choice_category_list: [],
          price_changes: {},
          sequence: 4,
          defaulted: false,
          available: true,
        },
        {
          id: "106512970",
          description: "50 Piece Wings",
          price: {
            amount: 7999,
            currency: "USD",
          },
          delivery_price: {
            amount: 7999,
            currency: "USD",
          },
          pickup_price: {
            amount: 7999,
            currency: "USD",
          },
          tax: 10.25,
          tax_rate: {
            name: "RestaurantTax",
            rate: 10.25,
            included_in_item_price: false,
          },
          choice_category_list: [],
          price_changes: {},
          sequence: 5,
          defaulted: false,
          available: true,
        },
      ],
      variation_target: true,
      sequence: 1,
    },
    {
      uuid: "SJvR4F3DEeyV_h08xaJvqg",
      id: "11402839471",
      name: "Choose a flavor wings",
      min_choice_options: 1,
      max_choice_options: 1,
      choice_option_list: [
        {
          uuid: "KL8U4F3DEeyV_h08xaJvqg",
          id: "11402839405",
          description: " Lemon Pepper",
          price: {
            amount: 0,
            currency: "USD",
          },
          delivery_price: {
            amount: 0,
            currency: "USD",
          },
          pickup_price: {
            amount: 0,
            currency: "USD",
          },
          miscellaneous_taxes: [],
          choice_category_list: [],
          price_changes: {},
          sequence: 1,
          defaulted: false,
          tags: [],
          available: true,
        },
        {
          uuid: "EXSOoF3DEeyV_h08xaJvqg",
          id: "11402839433",
          description: " Buffalo (Mild)",
          price: {
            amount: 0,
            currency: "USD",
          },
          delivery_price: {
            amount: 0,
            currency: "USD",
          },
          pickup_price: {
            amount: 0,
            currency: "USD",
          },
          miscellaneous_taxes: [],
          choice_category_list: [],
          price_changes: {},
          sequence: 2,
          defaulted: false,
          tags: [],
          available: true,
        },
        {
          uuid: "KwJOIF3DEeyV_h08xaJvqg",
          id: "11402839434",
          description: " Lime Chile",
          price: {
            amount: 0,
            currency: "USD",
          },
          delivery_price: {
            amount: 0,
            currency: "USD",
          },
          pickup_price: {
            amount: 0,
            currency: "USD",
          },
          miscellaneous_taxes: [],
          choice_category_list: [],
          price_changes: {},
          sequence: 3,
          defaulted: false,
          tags: [],
          available: true,
        },
        {
          uuid: "Lc-e8F3DEeyV_h08xaJvqg",
          id: "11402839447",
          description: " Spicy Honey BBQ",
          price: {
            amount: 0,
            currency: "USD",
          },
          delivery_price: {
            amount: 0,
            currency: "USD",
          },
          pickup_price: {
            amount: 0,
            currency: "USD",
          },
          miscellaneous_taxes: [],
          choice_category_list: [],
          price_changes: {},
          sequence: 4,
          defaulted: false,
          tags: [],
          available: true,
        },
        {
          uuid: "JqVcoF3DEeyV_h08xaJvqg",
          id: "11402839426",
          description: "Hot",
          price: {
            amount: 0,
            currency: "USD",
          },
          delivery_price: {
            amount: 0,
            currency: "USD",
          },
          pickup_price: {
            amount: 0,
            currency: "USD",
          },
          miscellaneous_taxes: [],
          choice_category_list: [],
          price_changes: {},
          sequence: 5,
          defaulted: false,
          tags: [],
          available: true,
        },
      ],
      variation_target: false,
      item_variation_id: 11335230,
      sequence: 2,
      display_settings: {
        display_type: "MODIFIER_ACTION_CHOOSE_ONE",
      },
    },
  ],
  tag_list: [],
  media_image: {
    base_url: "https://media-cdn.grubhub.com/image/upload/",
    public_id: "gjggd9q5jybfrqzboclc",
    format: "jpg",
    tag: "food",
    scale_mode: "FIT",
  },
  dishes: ["appetizers", "wings"],
  allowable_order_types: ["standard"],
  lead_time_ms: 0,
  menu_item_features: [],
  in_store_only: false,
  gh_pos_only: false,
  routing_tags: [],
  item_coupon: false,
  popular: false,
  deleted: false,
};
